In [189]:
import numpy as np
import matplotlib.pyplot as plt
import os

import mne
from mne.viz import plot_topomap
from scipy.stats import kurtosis
import csv

from load_dataset import *

In [ ]:
file_path = 'data/sub-CC110037/meg/passive_raw.fif'
raw, sampling_rate = load_raw_data(file_path)

In [ ]:
eog = get_eog_channels(raw)

In [ ]:
raw.first_samp

In [ ]:
eye_blink_threshold, time_points_array = get_eye_blink_time_points_array(eog)

In [ ]:
peaks = get_peak_time_point(time_points_array)

In [ ]:
np.set_printoptions(threshold=np.nan)
time_points_array

In [ ]:
start = time_points_array[0]
end = time_points_array[0]
peaks = []
stored = time_points_array[0:5]
for i in range(0, len(time_points_array)):
    if time_points_array[i] not in stored and (time_points_array[i]-1) not in stored:
        end = time_points_array[i-1]
        peak = start + int((end - start)/2)
        peaks.append(peak)
        start = time_points_array[i]
    if i >= 4:
        stored = time_points_array[i-4:i+1]

In [ ]:
peaks

In [ ]:
dir_list = os.listdir('data')

In [ ]:
data, data_sti = load_data_events('sub-CC110033', 0.1)

In [ ]:
raw, sampling_rate = load_raw_data(file_path)
data_preprocessed = preprocessing(raw)

# add stimulus channel
# positive = 1, negative = 2
data_sti = addchannel(data_preprocessed)
eog = get_eog_channels(raw)
eye_blink_threshold, time_points_array = get_eye_blink_time_points_array(eog)
eye_blink_peaks = get_peak_time_point(time_points_array)
non_eye_blink_peaks = random_markers(0.1, sampling_rate, eye_blink_peaks)
eye_blink_pos = []
eye_blink_neg = []
for i in eye_blink_peaks:
    if i >= 15000 and i <= 161999:
        eye_blink_pos.append(i)
for j in non_eye_blink_peaks:
    if j >= 15000 and j <=161999:
        eye_blink_neg.append(i)
event_1 = eye_blink_pos + eye_blink_neg
event_2 = [0] * (len(eye_blink_pos)+len(eye_blink_neg))
event_3 = [1] * len(eye_blink_pos) + [2] * len(eye_blink_neg)
events = np.array([event_1, event_2, event_3]).T

In [ ]:
events

In [ ]:
data_sti.add_events(events, stim_channel='STI')

In [ ]:
np.where(eye_blink_peaks>15000)

In [ ]:
eye_blink_pos

In [201]:
train_x_orig, test_x_orig, train_y_orig, test_y_orig = load_dataset(window_size=0.1, test_size=0.2, random_state=0)

Start loading data...
From dataset: sub-CC223286
Opening raw data file /Users/mlion0200/GitRepo/eye_blink_detection/data/sub-CC223286/meg/passive_raw.fif...
    Read a total of 8 projection items:
        mag_ssp_upright.fif : PCA-mags-v1 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v2 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v3 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v4 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v5 (1 x 306)  idle
        grad_ssp_upright.fif : PCA-grad-v1 (1 x 306)  idle
        grad_ssp_upright.fif : PCA-grad-v2 (1 x 306)  idle
        grad_ssp_upright.fif : PCA-grad-v3 (1 x 306)  idle
    Range : 19000 ... 166999 =     19.000 ...   166.999 secs
Ready.
Current compensation grade : 0
Reading 0 ... 147999  =      0.000 ...   147.999 secs...
Filtering a subset of channels. The highpass and lowpass values in the measurement info will not be updated.
Setting up band-pass filter from 3 - 70 Hz
l_trans_bandwidth chosen to 

0 bad epochs dropped
3 matching events found
No baseline correction applied
Not setting metadata
Created an SSP operator (subspace dimension = 3)
8 projection items activated
Loading data for 3 events and 101 original time points ...
0 bad epochs dropped
<Epochs  |   3 events (all good), -0.05 - 0.05 sec, baseline off, ~13.0 MB, data loaded,
 'negative': 2
 'positive': 1>
(3, 204, 101)
[2 1 2]
Start loading data...
From dataset: sub-CC222797
Opening raw data file /Users/mlion0200/GitRepo/eye_blink_detection/data/sub-CC222797/meg/passive_raw.fif...
    Read a total of 8 projection items:
        mag_ssp_upright.fif : PCA-mags-v1 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v2 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v3 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v4 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v5 (1 x 306)  idle
        grad_ssp_upright.fif : PCA-grad-v1 (1 x 306)  idle
        grad_ssp_upright.fif : PCA-grad-v2 (1 x 306)  idl

Setting up band-pass filter from 1 - 15 Hz
21 events found
Event IDs: [1 2]
21 matching events found
No baseline correction applied
Not setting metadata
Created an SSP operator (subspace dimension = 3)
Loading data for 21 events and 101 original time points ...
0 bad epochs dropped
21 matching events found
No baseline correction applied
Not setting metadata
Created an SSP operator (subspace dimension = 3)
8 projection items activated
Loading data for 21 events and 101 original time points ...
0 bad epochs dropped
<Epochs  |   21 events (all good), -0.05 - 0.05 sec, baseline off, ~15.8 MB, data loaded,
 'negative': 11
 'positive': 10>
(21, 204, 101)
[2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
Start loading data...
From dataset: sub-CC320002
Opening raw data file /Users/mlion0200/GitRepo/eye_blink_detection/data/sub-CC320002/meg/passive_raw.fif...
    Read a total of 8 projection items:
        mag_ssp_upright.fif : PCA-mags-v1 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v2 (1

Setting up band-stop filter from 59 - 61 Hz
Filter length of 6601 samples (6.601 sec) selected
Creating RawArray with float64 data, n_channels=1, n_times=152000
    Range : 0 ... 151999 =      0.000 ...   151.999 secs
Ready.
Filtering a subset of channels. The highpass and lowpass values in the measurement info will not be updated.
Setting up band-pass filter from 1 - 15 Hz
48 events found
Event IDs: [1 2]
48 matching events found
No baseline correction applied
Not setting metadata
Created an SSP operator (subspace dimension = 3)
Loading data for 48 events and 101 original time points ...
0 bad epochs dropped
48 matching events found
No baseline correction applied
Not setting metadata
Created an SSP operator (subspace dimension = 3)
8 projection items activated
Loading data for 48 events and 101 original time points ...
0 bad epochs dropped
<Epochs  |   48 events (all good), -0.05 - 0.05 sec, baseline off, ~20.0 MB, data loaded,
 'negative': 24
 'positive': 24>
(48, 204, 101)
[2 1 2 1 

Ready.
Current compensation grade : 0
Reading 0 ... 145999  =      0.000 ...   145.999 secs...
Filtering a subset of channels. The highpass and lowpass values in the measurement info will not be updated.
Setting up band-pass filter from 3 - 70 Hz
l_trans_bandwidth chosen to be 2.0 Hz
h_trans_bandwidth chosen to be 17.5 Hz
Filter length of 1651 samples (1.651 sec) selected
Setting up band-stop filter from 59 - 61 Hz
Filter length of 6601 samples (6.601 sec) selected
Creating RawArray with float64 data, n_channels=1, n_times=146000
    Range : 0 ... 145999 =      0.000 ...   145.999 secs
Ready.
Filtering a subset of channels. The highpass and lowpass values in the measurement info will not be updated.
Setting up band-pass filter from 1 - 15 Hz
5 events found
Event IDs: [1 2]
5 matching events found
No baseline correction applied
Not setting metadata
Created an SSP operator (subspace dimension = 3)
Loading data for 5 events and 101 original time points ...
0 bad epochs dropped
5 matching 

        mag_ssp_upright.fif : PCA-mags-v3 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v4 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v5 (1 x 306)  idle
        grad_ssp_upright.fif : PCA-grad-v1 (1 x 306)  idle
        grad_ssp_upright.fif : PCA-grad-v2 (1 x 306)  idle
        grad_ssp_upright.fif : PCA-grad-v3 (1 x 306)  idle
    Range : 16000 ... 162999 =     16.000 ...   162.999 secs
Ready.
Current compensation grade : 0
Reading 0 ... 146999  =      0.000 ...   146.999 secs...
Filtering a subset of channels. The highpass and lowpass values in the measurement info will not be updated.
Setting up band-pass filter from 3 - 70 Hz
l_trans_bandwidth chosen to be 2.0 Hz
h_trans_bandwidth chosen to be 17.5 Hz
Filter length of 1651 samples (1.651 sec) selected
Setting up band-stop filter from 59 - 61 Hz
Filter length of 6601 samples (6.601 sec) selected
Creating RawArray with float64 data, n_channels=1, n_times=147000
    Range : 0 ... 146999 =      0.000 ...   146.999 

Start loading data...
From dataset: sub-CC221977
Opening raw data file /Users/mlion0200/GitRepo/eye_blink_detection/data/sub-CC221977/meg/passive_raw.fif...
    Read a total of 8 projection items:
        mag_ssp_upright.fif : PCA-mags-v1 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v2 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v3 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v4 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v5 (1 x 306)  idle
        grad_ssp_upright.fif : PCA-grad-v1 (1 x 306)  idle
        grad_ssp_upright.fif : PCA-grad-v2 (1 x 306)  idle
        grad_ssp_upright.fif : PCA-grad-v3 (1 x 306)  idle
    Range : 21000 ... 169999 =     21.000 ...   169.999 secs
Ready.
Current compensation grade : 0
Reading 0 ... 148999  =      0.000 ...   148.999 secs...
Filtering a subset of channels. The highpass and lowpass values in the measurement info will not be updated.
Setting up band-pass filter from 3 - 70 Hz
l_trans_bandwidth chosen to 

Loading data for 31 events and 101 original time points ...
0 bad epochs dropped
<Epochs  |   31 events (all good), -0.05 - 0.05 sec, baseline off, ~17.4 MB, data loaded,
 'negative': 16
 'positive': 15>
(31, 204, 101)
[2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
Start loading data...
From dataset: sub-CC222367
Opening raw data file /Users/mlion0200/GitRepo/eye_blink_detection/data/sub-CC222367/meg/passive_raw.fif...
    Read a total of 8 projection items:
        mag_ssp_upright.fif : PCA-mags-v1 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v2 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v3 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v4 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v5 (1 x 306)  idle
        grad_ssp_upright.fif : PCA-grad-v1 (1 x 306)  idle
        grad_ssp_upright.fif : PCA-grad-v2 (1 x 306)  idle
        grad_ssp_upright.fif : PCA-grad-v3 (1 x 306)  idle
    Range : 20000 ... 166999 =     20.000 ...   166.9

l_trans_bandwidth chosen to be 2.0 Hz
h_trans_bandwidth chosen to be 17.5 Hz
Filter length of 1651 samples (1.651 sec) selected
Setting up band-stop filter from 59 - 61 Hz
Filter length of 6601 samples (6.601 sec) selected
Creating RawArray with float64 data, n_channels=1, n_times=147000
    Range : 0 ... 146999 =      0.000 ...   146.999 secs
Ready.
Filtering a subset of channels. The highpass and lowpass values in the measurement info will not be updated.
Setting up band-pass filter from 1 - 15 Hz
51 events found
Event IDs: [1 2]
51 matching events found
No baseline correction applied
Not setting metadata
Created an SSP operator (subspace dimension = 3)
Loading data for 51 events and 101 original time points ...
0 bad epochs dropped
51 matching events found
No baseline correction applied
Not setting metadata
Created an SSP operator (subspace dimension = 3)
8 projection items activated
Loading data for 51 events and 101 original time points ...
0 bad epochs dropped
<Epochs  |   51 eve

        grad_ssp_upright.fif : PCA-grad-v2 (1 x 306)  idle
        grad_ssp_upright.fif : PCA-grad-v3 (1 x 306)  idle
    Range : 14000 ... 161999 =     14.000 ...   161.999 secs
Ready.
Current compensation grade : 0
Reading 0 ... 147999  =      0.000 ...   147.999 secs...
Filtering a subset of channels. The highpass and lowpass values in the measurement info will not be updated.
Setting up band-pass filter from 3 - 70 Hz
l_trans_bandwidth chosen to be 2.0 Hz
h_trans_bandwidth chosen to be 17.5 Hz
Filter length of 1651 samples (1.651 sec) selected
Setting up band-stop filter from 59 - 61 Hz
Filter length of 6601 samples (6.601 sec) selected
Creating RawArray with float64 data, n_channels=1, n_times=148000
    Range : 0 ... 147999 =      0.000 ...   147.999 secs
Ready.
Filtering a subset of channels. The highpass and lowpass values in the measurement info will not be updated.
Setting up band-pass filter from 1 - 15 Hz
8 events found
Event IDs: [1 2]
8 matching events found
No baseline c

    Read a total of 8 projection items:
        mag_ssp_upright.fif : PCA-mags-v1 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v2 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v3 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v4 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v5 (1 x 306)  idle
        grad_ssp_upright.fif : PCA-grad-v1 (1 x 306)  idle
        grad_ssp_upright.fif : PCA-grad-v2 (1 x 306)  idle
        grad_ssp_upright.fif : PCA-grad-v3 (1 x 306)  idle
    Range : 39000 ... 184999 =     39.000 ...   184.999 secs
Ready.
Current compensation grade : 0
Reading 0 ... 145999  =      0.000 ...   145.999 secs...
Filtering a subset of channels. The highpass and lowpass values in the measurement info will not be updated.
Setting up band-pass filter from 3 - 70 Hz
l_trans_bandwidth chosen to be 2.0 Hz
h_trans_bandwidth chosen to be 17.5 Hz
Filter length of 1651 samples (1.651 sec) selected
Setting up band-stop filter from 59 - 61 Hz
Filter length

<Epochs  |   33 events (all good), -0.05 - 0.05 sec, baseline off, ~17.7 MB, data loaded,
 'negative': 16
 'positive': 17>
(33, 204, 101)
[1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1]
Start loading data...
From dataset: sub-CC221954
Opening raw data file /Users/mlion0200/GitRepo/eye_blink_detection/data/sub-CC221954/meg/passive_raw.fif...
    Read a total of 8 projection items:
        mag_ssp_upright.fif : PCA-mags-v1 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v2 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v3 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v4 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v5 (1 x 306)  idle
        grad_ssp_upright.fif : PCA-grad-v1 (1 x 306)  idle
        grad_ssp_upright.fif : PCA-grad-v2 (1 x 306)  idle
        grad_ssp_upright.fif : PCA-grad-v3 (1 x 306)  idle
    Range : 28000 ... 175999 =     28.000 ...   175.999 secs
Ready.
Current compensation grade : 0
Reading 0 ... 147999  =      0.

0 bad epochs dropped
6 matching events found
No baseline correction applied
Not setting metadata
Created an SSP operator (subspace dimension = 3)
8 projection items activated
Loading data for 6 events and 101 original time points ...
0 bad epochs dropped
<Epochs  |   6 events (all good), -0.05 - 0.05 sec, baseline off, ~13.4 MB, data loaded,
 'negative': 3
 'positive': 3>
(6, 204, 101)
[1 2 1 2 1 2]
Start loading data...
From dataset: sub-CC310331
Opening raw data file /Users/mlion0200/GitRepo/eye_blink_detection/data/sub-CC310331/meg/passive_raw.fif...
    Read a total of 8 projection items:
        mag_ssp_upright.fif : PCA-mags-v1 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v2 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v3 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v4 (1 x 306)  idle
        mag_ssp_upright.fif : PCA-mags-v5 (1 x 306)  idle
        grad_ssp_upright.fif : PCA-grad-v1 (1 x 306)  idle
        grad_ssp_upright.fif : PCA-grad-v2 (1 x 306

Setting up band-pass filter from 1 - 15 Hz
9 events found
Event IDs: [1 2]
9 matching events found
No baseline correction applied
Not setting metadata
Created an SSP operator (subspace dimension = 3)
Loading data for 9 events and 101 original time points ...
0 bad epochs dropped
9 matching events found
No baseline correction applied
Not setting metadata
Created an SSP operator (subspace dimension = 3)
8 projection items activated
Loading data for 9 events and 101 original time points ...
0 bad epochs dropped
<Epochs  |   9 events (all good), -0.05 - 0.05 sec, baseline off, ~13.9 MB, data loaded,
 'negative': 5
 'positive': 4>
(9, 204, 101)
[2 1 2 1 2 1 2 1 2]


In [202]:
train_x_array = np.asarray(train_x_orig)
test_x_array = np.asarray(test_x_orig)
train_y_array = np.asarray(train_y_orig)
test_y_array = np.asarray(test_y_orig)
m_train = train_x_array.shape[0]
num_px = train_x_array.shape[1]
m_test = test_x_array.shape[0]

print ("Number of training examples: " + str(m_train))
print ("Number of testing examples: " + str(m_test))
print ("train_x_orig shape: " + str(train_x_array.shape))
print ("train_y shape: " + str(train_y_array.shape))
print ("test_x_orig shape: " + str(test_x_array.shape))
print ("test_y shape: " + str(test_y_array.shape))

Number of training examples: 1359
Number of testing examples: 340
train_x_orig shape: (1359, 204, 101)
train_y shape: (1359,)
test_x_orig shape: (340, 204, 101)
test_y shape: (340,)


In [40]:
def norm_and_reshape(train_x, test_x):
    train_x_norm = train_x_array.reshape(train_x_array.shape[0], train_x_array.shape[1] * train_x_array.shape[2])
    test_x_norm = test_x_array.reshape(test_x_array.shape[0], test_x_array.shape[1] * test_x_array.shape[2])
    train_x = normalize(train_x_norm, norm='l2')
    test_x = normalize(test_x_norm, norm='l2')
    return train_x, test_x

In [142]:
def reshape_x(train_x, test_x):
    train_x_reshape = train_x_array.reshape(train_x_array.shape[0], train_x_array.shape[1] * train_x_array.shape[2])
    test_x_reshape = test_x_array.reshape(test_x_array.shape[0], test_x_array.shape[1] * test_x_array.shape[2])
    return train_x_reshape, test_x_reshape

In [119]:
def reshape_dimension(train_x, test_x):
    reshape_train_x = []
    reshape_test_x = []
    for x in train_x:
        reshape_train_x.append(np.asarray(x).T)
    for y in test_x:
        reshape_test_x.append(np.asarray(y).T)
    return reshape_train_x, reshape_test_x

In [41]:
train_x_norm, test_x_norm = norm_and_reshape(train_x_array, test_x_array)

In [143]:
train_x_reshape, test_x_reshape = reshape_x(train_x_array, test_x_array)

In [203]:
train_x_var = np.var(train_x_array, axis=1)
test_x_var = np.var(test_x_array, axis=1)

In [135]:
train_x_gradient_1 = []
test_x_gradient_1 = []
for train_x in train_x_array:
    train_x_gradient_1.append(np.gradient(train_x, axis=1))
for test_x in test_x_array:
    test_x_gradient_1.append(np.gradient(test_x, axis=1))

In [120]:
reshape_train_x_gradient_1, reshape_test_x_gradient_1 = reshape_dimension(train_x_gradient_1, test_x_gradient_1)

In [136]:
train_x_gradient_2 = []
test_x_gradient_2 = []
for train_x in train_x_array:
    train_x_gradient_2.append(np.gradient(train_x, 2, axis=1))
for test_x in test_x_array:
    test_x_gradient_2.append(np.gradient(test_x, 2, axis=1))

In [122]:
reshape_train_x_gradient_2, reshape_test_x_gradient_2 = reshape_dimension(train_x_gradient_2, test_x_gradient_2)

In [204]:
train_x_kurtosis = []
test_x_kurtosis = []
for train_x in train_x_array:
    train_x_kurtosis.append(kurtosis(train_x, axis=1))
for test_x in test_x_array:
    test_x_kurtosis.append(kurtosis(test_x, axis=1))

In [124]:
train_x_feature = []
train_x_feature.append(train_x_var)
train_x_feature.append(reshape_train_x_gradient_1)
train_x_feature.append(reshape_train_x_gradient_2)
train_x_feature.append(train_x_kurtosis)

In [175]:
len(appended)

248

In [137]:
appended = np.append(train_x_gradient_1, train_x_gradient_2, axis=1)

In [139]:
appended_test = np.append(test_x_gradient_1, test_x_gradient_2, axis=1)

In [125]:
test_x_feature = []
test_x_feature.append(test_x_var)
test_x_feature.append(reshape_test_x_gradient_1)
test_x_feature.append(reshape_test_x_gradient_2)
test_x_feature.append(test_x_kurtosis)

In [207]:
train_var_x_reshape, test_var_x_reshape = reshape_x(train_x_var, test_x_var)

In [145]:
train_x_gradient_1_reshape, test_x_gradient_1_reshape = reshape_x(train_x_gradient_1, test_x_gradient_1)

In [146]:
train_x_gradient_2_reshape, test_x_gradient_2_reshape = reshape_x(train_x_gradient_2, test_x_gradient_2)

In [208]:
train_kurtosis_x_reshape, test_kurtosis_x_reshape = reshape_x(train_x_kurtosis, test_x_kurtosis)

In [168]:
appended = np.append(train_x_gradient_1_reshape, train_x_gradient_2_reshape, axis=1)

In [169]:
appended = np.append(appended, train_var_x_reshape, axis=1)

In [170]:
appended = np.append(appended, train_kurtosis_x_reshape, axis=1)

In [171]:
appended_test = np.append(test_x_gradient_1_reshape, test_x_gradient_2_reshape, axis=1)

In [172]:
appended_test = np.append(appended_test, test_var_x_reshape, axis=1)

In [173]:
appended_test = np.append(appended_test, test_kurtosis_x_reshape, axis=1)

In [209]:
# Only use variance and kurtosis
appended = np.append(train_var_x_reshape, train_kurtosis_x_reshape, axis=1)
appended_test = np.append(test_var_x_reshape, test_kurtosis_x_reshape, axis=1)

In [80]:
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

In [81]:
names = ["Nearest Neighbors", "Linear SVM", "RBF SVM", "Gaussian Process",
         "Decision Tree", "Random Forest", "Neural Net", "AdaBoost",
         "Naive Bayes", "QDA"]

In [82]:
classifiers = [
    KNeighborsClassifier(3),
    SVC(kernel="linear", C=0.025),
    SVC(gamma=2, C=1),
    GaussianProcessClassifier(1.0 * RBF(1.0)),
    DecisionTreeClassifier(max_depth=5),
    RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1),
    MLPClassifier(alpha=1),
    AdaBoostClassifier(),
    GaussianNB(),
    QuadraticDiscriminantAnalysis()]

In [210]:
for name, clf in zip(names, classifiers):
    clf.fit(appended, train_y_array)
    score = clf.score(appended_test, test_y_array)
    print(name, 'Score: ', score)

Nearest Neighbors Score:  0.5323529411764706
Linear SVM Score:  0.47941176470588237
RBF SVM Score:  0.47941176470588237


KeyboardInterrupt: 

In [181]:
nb = GaussianNB()
nb.fit(appended, train_y_array)

GaussianNB(priors=None, var_smoothing=1e-09)

In [182]:
print(nb.predict(appended_test))
print(test_y_array)

[1 2 2 2 2 2 1 2 1 1 2 1 1 2 2 2 2 2 1 2 2 1 1 2 1 2 2 1 1 2 2 1 1 1 2 1 1
 1 2 2 1 1 1 1 1 2 2 1 1 2 2 2 1 2 2 1 1 1 1 1 1 1]
[1 2 1 2 2 2 2 1 2 1 1 1 2 2 1 1 2 1 2 2 1 1 1 1 2 2 2 2 2 1 2 1 2 2 1 1 2
 1 2 2 2 1 1 1 2 1 2 2 1 1 1 1 2 1 1 1 1 1 1 2 2 1]


In [134]:
len(appended[0][0])

204

In [105]:
np.gradient(np.array([[1, 2, 6], [3, 4, 5]], dtype=float))

[array([[ 2.,  2., -1.],
        [ 2.,  2., -1.]]), array([[1. , 2.5, 4. ],
        [1. , 1. , 1. ]])]

In [107]:
np.gradient(np.array([[1, 2, 6], [3, 4, 5]], dtype=float), axis=1)

array([[1. , 2.5, 4. ],
       [1. , 1. , 1. ]])